// get planets by its ID 
GET http://localhost:3000/planets/621ff30d2a3e781873fcb65c
Content-Type: application/json
// another planet just testing
###

/// Adding a planet 
###
GET http://localhost:3000/planets
Content-Type: application/json

###

DELETE http://localhost:3000/planets/621ff30d2a3e781873fcb661
Content-Type: application/json

###
PATCH  http://localhost:3000/planets/
Content-Type: application/json

{
    "name": "Fabtopia",
    "description": "updated planet details"
}