
GET http://localhost:3000/planets
Content-Type: application/json

###

GET http://localhost:3000/planets/621ff30d2a3e781873fcb65c
Content-Type: application/json
// another planet just testing
###
GET http://localhost:3000/planets/621ff30d2a3e781873fcb65f
###
# adding planet
PATCH  http://localhost:3000/planets/621ff30d2a3e781873fcb65f
Content-Type: application/json

{
    "name": "fabulous land",
    "description": "greatest planet around"
}

###

DELETE http://localhost:3000/planets/621ff30d2a3e781873fcb661
Content-Type: application/json

### 
